clusterName: accor-resilient-eks-dev
serviceAccount:
  create: true
  name: aws-load-balancer-controller
vpcId: vpc-0f6821a3a60ab2597 

featureGates:
  ALBGatewayAPI: true

gatewayClassConfig:
  name: accor-aws-alb
  controllerName: gateway.k8s.aws/alb
  parametersRef:
    group: gateway.k8s.aws
    kind: LoadBalancerConfiguration
    name: alb-public-ip
    namespace: default