apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RaymondHtue/acr-sre-gitops.git
    targetRevision: HEAD
    path: aws-alb-manifests
    directory:
      recurse: true
      exclude: aws-alb-application.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Validate=false
