args:
  - --kubelet-preferred-address-types=InternalIP
  - --kubelet-insecure-tls

replicas: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    memory: 200Mi
